/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AppRouteImport } from './routes/app'
import { Route as ApplyRouteImport } from './routes/apply'
import { Route as CarsRouteImport } from './routes/cars'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as DeliveriesRouteImport } from './routes/deliveries'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as EarningsRouteImport } from './routes/earnings'
import { Route as LocalRouteImport } from './routes/local'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ShareStuffRouteImport } from './routes/share-stuff'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as TripsRouteImport } from './routes/trips'
import { Route as VolunteerRouteImport } from './routes/volunteer'
import { Route as ApplyDeliveryRouteImport } from './routes/apply.delivery'
import { Route as ApplyDriverRouteImport } from './routes/apply.driver'
import { Route as ApplyRiderRouteImport } from './routes/apply.rider'
import { Route as CarsNewRouteImport } from './routes/cars.new'
import { Route as DeliveriesRequestRouteImport } from './routes/deliveries.request'
import { Route as MessagesIdRouteImport } from './routes/messages.$id'
import { Route as RidesIndexRouteImport } from './routes/rides.index'
import { Route as RidesIdRouteImport } from './routes/rides.$id'
import { Route as RidesPostRouteImport } from './routes/rides.post'
import { Route as RidesRequestsRouteImport } from './routes/rides.requests'
import { Route as ShareStuffNewRouteImport } from './routes/share-stuff.new'
import { Route as TrackCodeRouteImport } from './routes/track.$code'
import { Route as VolunteerNewRouteImport } from './routes/volunteer.new'
import { Route as RidesRequestNewRouteImport } from './routes/rides.request.new'
import { Route as RidesRequestsIdRouteImport } from './routes/rides.requests.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplyRoute = ApplyRouteImport.update({
  id: '/apply',
  path: '/apply',
  getParentRoute: () => rootRouteImport,
} as any)
const CarsRoute = CarsRouteImport.update({
  id: '/cars',
  path: '/cars',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const DeliveriesRoute = DeliveriesRouteImport.update({
  id: '/deliveries',
  path: '/deliveries',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const EarningsRoute = EarningsRouteImport.update({
  id: '/earnings',
  path: '/earnings',
  getParentRoute: () => rootRouteImport,
} as any)
const LocalRoute = LocalRouteImport.update({
  id: '/local',
  path: '/local',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ShareStuffRoute = ShareStuffRouteImport.update({
  id: '/share-stuff',
  path: '/share-stuff',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const TripsRoute = TripsRouteImport.update({
  id: '/trips',
  path: '/trips',
  getParentRoute: () => rootRouteImport,
} as any)
const VolunteerRoute = VolunteerRouteImport.update({
  id: '/volunteer',
  path: '/volunteer',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplyDeliveryRoute = ApplyDeliveryRouteImport.update({
  id: '/delivery',
  path: '/delivery',
  getParentRoute: () => ApplyRoute,
} as any)
const ApplyDriverRoute = ApplyDriverRouteImport.update({
  id: '/driver',
  path: '/driver',
  getParentRoute: () => ApplyRoute,
} as any)
const ApplyRiderRoute = ApplyRiderRouteImport.update({
  id: '/rider',
  path: '/rider',
  getParentRoute: () => ApplyRoute,
} as any)
const CarsNewRoute = CarsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => CarsRoute,
} as any)
const DeliveriesRequestRoute = DeliveriesRequestRouteImport.update({
  id: '/request',
  path: '/request',
  getParentRoute: () => DeliveriesRoute,
} as any)
const MessagesIdRoute = MessagesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => MessagesRoute,
} as any)
const RidesIndexRoute = RidesIndexRouteImport.update({
  id: '/rides/',
  path: '/rides/',
  getParentRoute: () => rootRouteImport,
} as any)
const RidesIdRoute = RidesIdRouteImport.update({
  id: '/rides/$id',
  path: '/rides/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const RidesPostRoute = RidesPostRouteImport.update({
  id: '/rides/post',
  path: '/rides/post',
  getParentRoute: () => rootRouteImport,
} as any)
const RidesRequestsRoute = RidesRequestsRouteImport.update({
  id: '/rides/requests',
  path: '/rides/requests',
  getParentRoute: () => rootRouteImport,
} as any)
const ShareStuffNewRoute = ShareStuffNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => ShareStuffRoute,
} as any)
const TrackCodeRoute = TrackCodeRouteImport.update({
  id: '/track/$code',
  path: '/track/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const VolunteerNewRoute = VolunteerNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => VolunteerRoute,
} as any)
const RidesRequestNewRoute = RidesRequestNewRouteImport.update({
  id: '/rides/request/new',
  path: '/rides/request/new',
  getParentRoute: () => rootRouteImport,
} as any)
const RidesRequestsIdRoute = RidesRequestsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => RidesRequestsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/app': typeof AppRoute
  '/apply': typeof ApplyRouteWithChildren
  '/cars': typeof CarsRouteWithChildren
  '/checkout': typeof CheckoutRoute
  '/deliveries': typeof DeliveriesRouteWithChildren
  '/demo': typeof DemoRoute
  '/earnings': typeof EarningsRoute
  '/local': typeof LocalRoute
  '/messages': typeof MessagesRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/share-stuff': typeof ShareStuffRouteWithChildren
  '/terms': typeof TermsRoute
  '/trips': typeof TripsRoute
  '/volunteer': typeof VolunteerRouteWithChildren
  '/apply/delivery': typeof ApplyDeliveryRoute
  '/apply/driver': typeof ApplyDriverRoute
  '/apply/rider': typeof ApplyRiderRoute
  '/cars/new': typeof CarsNewRoute
  '/deliveries/request': typeof DeliveriesRequestRoute
  '/messages/$id': typeof MessagesIdRoute
  '/rides/$id': typeof RidesIdRoute
  '/rides/post': typeof RidesPostRoute
  '/rides/requests': typeof RidesRequestsRouteWithChildren
  '/share-stuff/new': typeof ShareStuffNewRoute
  '/track/$code': typeof TrackCodeRoute
  '/volunteer/new': typeof VolunteerNewRoute
  '/rides/': typeof RidesIndexRoute
  '/rides/request/new': typeof RidesRequestNewRoute
  '/rides/requests/$id': typeof RidesRequestsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/app': typeof AppRoute
  '/apply': typeof ApplyRouteWithChildren
  '/cars': typeof CarsRouteWithChildren
  '/checkout': typeof CheckoutRoute
  '/deliveries': typeof DeliveriesRouteWithChildren
  '/demo': typeof DemoRoute
  '/earnings': typeof EarningsRoute
  '/local': typeof LocalRoute
  '/messages': typeof MessagesRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/share-stuff': typeof ShareStuffRouteWithChildren
  '/terms': typeof TermsRoute
  '/trips': typeof TripsRoute
  '/volunteer': typeof VolunteerRouteWithChildren
  '/apply/delivery': typeof ApplyDeliveryRoute
  '/apply/driver': typeof ApplyDriverRoute
  '/apply/rider': typeof ApplyRiderRoute
  '/cars/new': typeof CarsNewRoute
  '/deliveries/request': typeof DeliveriesRequestRoute
  '/messages/$id': typeof MessagesIdRoute
  '/rides/$id': typeof RidesIdRoute
  '/rides/post': typeof RidesPostRoute
  '/rides/requests': typeof RidesRequestsRouteWithChildren
  '/share-stuff/new': typeof ShareStuffNewRoute
  '/track/$code': typeof TrackCodeRoute
  '/volunteer/new': typeof VolunteerNewRoute
  '/rides': typeof RidesIndexRoute
  '/rides/request/new': typeof RidesRequestNewRoute
  '/rides/requests/$id': typeof RidesRequestsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/app': typeof AppRoute
  '/apply': typeof ApplyRouteWithChildren
  '/cars': typeof CarsRouteWithChildren
  '/checkout': typeof CheckoutRoute
  '/deliveries': typeof DeliveriesRouteWithChildren
  '/demo': typeof DemoRoute
  '/earnings': typeof EarningsRoute
  '/local': typeof LocalRoute
  '/messages': typeof MessagesRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/share-stuff': typeof ShareStuffRouteWithChildren
  '/terms': typeof TermsRoute
  '/trips': typeof TripsRoute
  '/volunteer': typeof VolunteerRouteWithChildren
  '/apply/delivery': typeof ApplyDeliveryRoute
  '/apply/driver': typeof ApplyDriverRoute
  '/apply/rider': typeof ApplyRiderRoute
  '/cars/new': typeof CarsNewRoute
  '/deliveries/request': typeof DeliveriesRequestRoute
  '/messages/$id': typeof MessagesIdRoute
  '/rides/$id': typeof RidesIdRoute
  '/rides/post': typeof RidesPostRoute
  '/rides/requests': typeof RidesRequestsRouteWithChildren
  '/share-stuff/new': typeof ShareStuffNewRoute
  '/track/$code': typeof TrackCodeRoute
  '/volunteer/new': typeof VolunteerNewRoute
  '/rides/': typeof RidesIndexRoute
  '/rides/request/new': typeof RidesRequestNewRoute
  '/rides/requests/$id': typeof RidesRequestsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/app'
    | '/apply'
    | '/cars'
    | '/checkout'
    | '/deliveries'
    | '/demo'
    | '/earnings'
    | '/local'
    | '/messages'
    | '/privacy'
    | '/profile'
    | '/share-stuff'
    | '/terms'
    | '/trips'
    | '/volunteer'
    | '/apply/delivery'
    | '/apply/driver'
    | '/apply/rider'
    | '/cars/new'
    | '/deliveries/request'
    | '/messages/$id'
    | '/rides/$id'
    | '/rides/post'
    | '/rides/requests'
    | '/share-stuff/new'
    | '/track/$code'
    | '/volunteer/new'
    | '/rides/'
    | '/rides/request/new'
    | '/rides/requests/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/app'
    | '/apply'
    | '/cars'
    | '/checkout'
    | '/deliveries'
    | '/demo'
    | '/earnings'
    | '/local'
    | '/messages'
    | '/privacy'
    | '/profile'
    | '/share-stuff'
    | '/terms'
    | '/trips'
    | '/volunteer'
    | '/apply/delivery'
    | '/apply/driver'
    | '/apply/rider'
    | '/cars/new'
    | '/deliveries/request'
    | '/messages/$id'
    | '/rides/$id'
    | '/rides/post'
    | '/rides/requests'
    | '/share-stuff/new'
    | '/track/$code'
    | '/volunteer/new'
    | '/rides'
    | '/rides/request/new'
    | '/rides/requests/$id'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/app'
    | '/apply'
    | '/cars'
    | '/checkout'
    | '/deliveries'
    | '/demo'
    | '/earnings'
    | '/local'
    | '/messages'
    | '/privacy'
    | '/profile'
    | '/share-stuff'
    | '/terms'
    | '/trips'
    | '/volunteer'
    | '/apply/delivery'
    | '/apply/driver'
    | '/apply/rider'
    | '/cars/new'
    | '/deliveries/request'
    | '/messages/$id'
    | '/rides/$id'
    | '/rides/post'
    | '/rides/requests'
    | '/share-stuff/new'
    | '/track/$code'
    | '/volunteer/new'
    | '/rides/'
    | '/rides/request/new'
    | '/rides/requests/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  AppRoute: typeof AppRoute
  ApplyRoute: typeof ApplyRouteWithChildren
  CarsRoute: typeof CarsRouteWithChildren
  CheckoutRoute: typeof CheckoutRoute
  DeliveriesRoute: typeof DeliveriesRouteWithChildren
  DemoRoute: typeof DemoRoute
  EarningsRoute: typeof EarningsRoute
  LocalRoute: typeof LocalRoute
  MessagesRoute: typeof MessagesRouteWithChildren
  PrivacyRoute: typeof PrivacyRoute
  ProfileRoute: typeof ProfileRoute
  ShareStuffRoute: typeof ShareStuffRouteWithChildren
  TermsRoute: typeof TermsRoute
  TripsRoute: typeof TripsRoute
  VolunteerRoute: typeof VolunteerRouteWithChildren
  RidesIdRoute: typeof RidesIdRoute
  RidesPostRoute: typeof RidesPostRoute
  RidesRequestsRoute: typeof RidesRequestsRouteWithChildren
  TrackCodeRoute: typeof TrackCodeRoute
  RidesIndexRoute: typeof RidesIndexRoute
  RidesRequestNewRoute: typeof RidesRequestNewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apply': {
      id: '/apply'
      path: '/apply'
      fullPath: '/apply'
      preLoaderRoute: typeof ApplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cars': {
      id: '/cars'
      path: '/cars'
      fullPath: '/cars'
      preLoaderRoute: typeof CarsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deliveries': {
      id: '/deliveries'
      path: '/deliveries'
      fullPath: '/deliveries'
      preLoaderRoute: typeof DeliveriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/earnings': {
      id: '/earnings'
      path: '/earnings'
      fullPath: '/earnings'
      preLoaderRoute: typeof EarningsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/local': {
      id: '/local'
      path: '/local'
      fullPath: '/local'
      preLoaderRoute: typeof LocalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/share-stuff': {
      id: '/share-stuff'
      path: '/share-stuff'
      fullPath: '/share-stuff'
      preLoaderRoute: typeof ShareStuffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trips': {
      id: '/trips'
      path: '/trips'
      fullPath: '/trips'
      preLoaderRoute: typeof TripsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/volunteer': {
      id: '/volunteer'
      path: '/volunteer'
      fullPath: '/volunteer'
      preLoaderRoute: typeof VolunteerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apply/delivery': {
      id: '/apply/delivery'
      path: '/delivery'
      fullPath: '/apply/delivery'
      preLoaderRoute: typeof ApplyDeliveryRouteImport
      parentRoute: typeof ApplyRoute
    }
    '/apply/driver': {
      id: '/apply/driver'
      path: '/driver'
      fullPath: '/apply/driver'
      preLoaderRoute: typeof ApplyDriverRouteImport
      parentRoute: typeof ApplyRoute
    }
    '/apply/rider': {
      id: '/apply/rider'
      path: '/rider'
      fullPath: '/apply/rider'
      preLoaderRoute: typeof ApplyRiderRouteImport
      parentRoute: typeof ApplyRoute
    }
    '/cars/new': {
      id: '/cars/new'
      path: '/new'
      fullPath: '/cars/new'
      preLoaderRoute: typeof CarsNewRouteImport
      parentRoute: typeof CarsRoute
    }
    '/deliveries/request': {
      id: '/deliveries/request'
      path: '/request'
      fullPath: '/deliveries/request'
      preLoaderRoute: typeof DeliveriesRequestRouteImport
      parentRoute: typeof DeliveriesRoute
    }
    '/messages/$id': {
      id: '/messages/$id'
      path: '/$id'
      fullPath: '/messages/$id'
      preLoaderRoute: typeof MessagesIdRouteImport
      parentRoute: typeof MessagesRoute
    }
    '/rides/': {
      id: '/rides/'
      path: '/rides'
      fullPath: '/rides/'
      preLoaderRoute: typeof RidesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rides/$id': {
      id: '/rides/$id'
      path: '/rides/$id'
      fullPath: '/rides/$id'
      preLoaderRoute: typeof RidesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rides/post': {
      id: '/rides/post'
      path: '/rides/post'
      fullPath: '/rides/post'
      preLoaderRoute: typeof RidesPostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rides/requests': {
      id: '/rides/requests'
      path: '/rides/requests'
      fullPath: '/rides/requests'
      preLoaderRoute: typeof RidesRequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/share-stuff/new': {
      id: '/share-stuff/new'
      path: '/new'
      fullPath: '/share-stuff/new'
      preLoaderRoute: typeof ShareStuffNewRouteImport
      parentRoute: typeof ShareStuffRoute
    }
    '/track/$code': {
      id: '/track/$code'
      path: '/track/$code'
      fullPath: '/track/$code'
      preLoaderRoute: typeof TrackCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/volunteer/new': {
      id: '/volunteer/new'
      path: '/new'
      fullPath: '/volunteer/new'
      preLoaderRoute: typeof VolunteerNewRouteImport
      parentRoute: typeof VolunteerRoute
    }
    '/rides/request/new': {
      id: '/rides/request/new'
      path: '/rides/request/new'
      fullPath: '/rides/request/new'
      preLoaderRoute: typeof RidesRequestNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rides/requests/$id': {
      id: '/rides/requests/$id'
      path: '/$id'
      fullPath: '/rides/requests/$id'
      preLoaderRoute: typeof RidesRequestsIdRouteImport
      parentRoute: typeof RidesRequestsRoute
    }
  }
}

interface ApplyRouteChildren {
  ApplyDeliveryRoute: typeof ApplyDeliveryRoute
  ApplyDriverRoute: typeof ApplyDriverRoute
  ApplyRiderRoute: typeof ApplyRiderRoute
}

const ApplyRouteChildren: ApplyRouteChildren = {
  ApplyDeliveryRoute: ApplyDeliveryRoute,
  ApplyDriverRoute: ApplyDriverRoute,
  ApplyRiderRoute: ApplyRiderRoute,
}

const ApplyRouteWithChildren = ApplyRoute._addFileChildren(ApplyRouteChildren)

interface CarsRouteChildren {
  CarsNewRoute: typeof CarsNewRoute
}

const CarsRouteChildren: CarsRouteChildren = {
  CarsNewRoute: CarsNewRoute,
}

const CarsRouteWithChildren = CarsRoute._addFileChildren(CarsRouteChildren)

interface DeliveriesRouteChildren {
  DeliveriesRequestRoute: typeof DeliveriesRequestRoute
}

const DeliveriesRouteChildren: DeliveriesRouteChildren = {
  DeliveriesRequestRoute: DeliveriesRequestRoute,
}

const DeliveriesRouteWithChildren = DeliveriesRoute._addFileChildren(
  DeliveriesRouteChildren,
)

interface MessagesRouteChildren {
  MessagesIdRoute: typeof MessagesIdRoute
}

const MessagesRouteChildren: MessagesRouteChildren = {
  MessagesIdRoute: MessagesIdRoute,
}

const MessagesRouteWithChildren = MessagesRoute._addFileChildren(
  MessagesRouteChildren,
)

interface ShareStuffRouteChildren {
  ShareStuffNewRoute: typeof ShareStuffNewRoute
}

const ShareStuffRouteChildren: ShareStuffRouteChildren = {
  ShareStuffNewRoute: ShareStuffNewRoute,
}

const ShareStuffRouteWithChildren = ShareStuffRoute._addFileChildren(
  ShareStuffRouteChildren,
)

interface VolunteerRouteChildren {
  VolunteerNewRoute: typeof VolunteerNewRoute
}

const VolunteerRouteChildren: VolunteerRouteChildren = {
  VolunteerNewRoute: VolunteerNewRoute,
}

const VolunteerRouteWithChildren = VolunteerRoute._addFileChildren(
  VolunteerRouteChildren,
)

interface RidesRequestsRouteChildren {
  RidesRequestsIdRoute: typeof RidesRequestsIdRoute
}

const RidesRequestsRouteChildren: RidesRequestsRouteChildren = {
  RidesRequestsIdRoute: RidesRequestsIdRoute,
}

const RidesRequestsRouteWithChildren = RidesRequestsRoute._addFileChildren(
  RidesRequestsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  AppRoute: AppRoute,
  ApplyRoute: ApplyRouteWithChildren,
  CarsRoute: CarsRouteWithChildren,
  CheckoutRoute: CheckoutRoute,
  DeliveriesRoute: DeliveriesRouteWithChildren,
  DemoRoute: DemoRoute,
  EarningsRoute: EarningsRoute,
  LocalRoute: LocalRoute,
  MessagesRoute: MessagesRouteWithChildren,
  PrivacyRoute: PrivacyRoute,
  ProfileRoute: ProfileRoute,
  ShareStuffRoute: ShareStuffRouteWithChildren,
  TermsRoute: TermsRoute,
  TripsRoute: TripsRoute,
  VolunteerRoute: VolunteerRouteWithChildren,
  RidesIdRoute: RidesIdRoute,
  RidesPostRoute: RidesPostRoute,
  RidesRequestsRoute: RidesRequestsRouteWithChildren,
  TrackCodeRoute: TrackCodeRoute,
  RidesIndexRoute: RidesIndexRoute,
  RidesRequestNewRoute: RidesRequestNewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
